version: '3'
services:
  web:
    build: .
    image: blown302/robocar-car-api
#    command: ['python3', '/app/repositories/data.py']
    command: ['python3', '/app/app.py']
    volumes:
      - .:/app
      - /Users/blown302/programming/ml/donkey-docker:/data
    ports:
      - 5000:5000
    restart: always
    environment:
      - BROKER_HOST=broker
      - PYTHONUNBUFFERED=0
  broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001